### ISSUE TITLE
messiness percentage

### ISSUE THREAD

**Issue by msgoussi** [nrennie/messy#13]
set.seed(1234)
ToothGrowth[1:10,] |> 
add_special_chars(cols = "supp", messiness = 0.5)

I got 7 values has changed not 5 values

![image](https://github.com/user-attachments/assets/24abcabc-b469-4479-9172-b34954a22cd3)

**Comment by Dynge** [comment]
Seems like the code for this function is probabilistic instead of deterministic. 

``` r
      if (stats::runif(1) < messiness) {
```

So that can explain why you dont get exactly half the columns changed.

**Comment by nrennie** [comment]
Yes, that's the way the function is designed (and why you have to set a random seed). Making this deterministic wouldn't really make sense e.g. if you have 10 rows and supply a value of 0.6741 - how many rows should be changed? Most of the time you won't only have 10 rows, so you won't see as much variation.

**Comment by Dynge** [comment]
One could do the way of some of the other methods and determine the number of rows by taking the closest number to the messiness score. That way it would be consistently the same amount of rows that got changed. This is how the method to duplicate data rows functions if I am not mistaken.

However as you say.. It does not really matter for the use case.
